# Generated by Django 5.1.5 on 2025-02-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_mealplanreminder_user_dob_user_fitness_stats_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('paleo', 'Paleo'), ('keto', 'Keto'), ('gluten_free', 'Gluten-Free'), ('non_vegetarian', 'Non-Vegetarian')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('gain_muscle', 'Gain Muscle'), ('lose_weight', 'Lose Weight'), ('maintain_fitness', 'Maintain Fitness'), ('increase_flexibility', 'Increase Flexibility'), ('improve_endurance', 'Improve Endurance')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='users.allergy'),
        ),
    ]
