# Generated by Django 5.1.5 on 2025-02-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_dob_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('none', 'No Preference')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('strength_training', 'Strength Training'), ('fat_burn', 'Fat Burn & Weight Loss'), ('endurance', 'Endurance & Stamina Boost'), ('flexibility', 'Flexibility & Mobility'), ('functional', 'Functional & Core Strength'), ('personalized', 'Personalized Workout & Meal Planning')], default='General Fitness', max_length=50, null=True),
        ),
    ]
