# Generated by Django 5.1.5 on 2025-02-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_user_is_staff_userprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dietary_preferences',
            field=models.CharField(blank=True, choices=[('vegetarian', 'Vegetarian'), ('non-vegetarian', 'Non-Vegetarian'), ('vegan', 'Vegan'), ('keto', 'Keto'), ('gluten_free', 'Gluten Free'), ('none', 'No Preference')], default='None', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fitness_goals',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss & Fat Burn'), ('muscle_gain', 'Muscle Gain & Strength Training'), ('endurance', 'Endurance & Stamina Boost'), ('flexibility', 'Flexibility & Mobility'), ('core_strength', 'Core & Functional Strength'), ('balanced_fitness', 'Balanced Fitness & Well-being'), ('athletic_performance', 'Athletic Performance & Conditioning'), ('custom_wellness', 'Customized & Holistic Wellness')], default='General Fitness', max_length=50, null=True),
        ),
    ]
