# Generated by Django 5.1.5 on 2025-02-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userprofile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='secret_key',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
