# Generated by Django 5.1.5 on 2025-02-18 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_userprofile_email_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
    ]
