# Generated by Django 5.1.5 on 2025-02-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
